# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ruby_app.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1", group: %i[development test]
gem "standard", group: %i[development test]
